on:
  pull_request:
    types: [closed]
jobs:
  apk:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release')}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: yarn install
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build APK
        run: cd android && ./gradlew assembleRelease
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: android/app/build/outputs/apk/release/app-release.apk
  release:
    name: Release APK
    needs: apk
    runs-on: ubuntu-latest
    steps:
      - id: get-id
        run: |
          id=$(echo ${{github.event.pull_request.title}} | cut -d ';' -f1)
          echo "id=$id" >> $GITHUB_OUTPUT
      - name: Download APK from build
        uses: actions/download-artifact@v1
        with:
          name: apk  
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get-id.outputs.id }}
          release_name: Release ${{ steps.get-id.outputs.id }}
          draft: false
          prerelease: false
      - name: Upload Release APK
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: apk/app-release.apk
          asset_name: AppRelease.apk
          asset_content_type: application/zip
