on:
  pull_request:
    branches:
      - master
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@master
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install node modules
        run: |
          yarn install
      - name: Run test
        run: |
          yarn test
      - name: Echo current directory
        run: |
          echo "$PWD"
      - name: CD android
        run: |
          cd android && echo "$PWD"
      - name: Echo current directory
        run: |
          echo "$PWD"
